### ISSUE TITLE
Logging of detection of non-Marathon apps is inconsistent

### ISSUE THREAD

**Issue by JayH5** [universalcore/consular#18]
Consular seems to claim that some apps are non-Marathon apps but registers them with Consular at a later point (on the next scan?). See [this](https://gist.github.com/JayH5/01a82923bd8e995ea9ac) log for an example.

To be clear, this doesn't seem like a functional error, but the logs are confusing to read.

**Comment by smn** [comment]
That is odd, I'll look at what's going on and see if it's either a bug or if logging needs to be changed.

**Comment by JayH5** [comment]
Should be solved by #23
